Search.appendIndex(
    [
                {
            "fqsen": "\\Murdej\\Arrays",
            "name": "Arrays",
            "summary": "",
            "url": "classes/Murdej-Arrays.html"
        },                {
            "fqsen": "\\Murdej\\Arrays\u003A\u003AaddDefaultsRecursive\u0028\u0029",
            "name": "addDefaultsRecursive",
            "summary": "Recursively\u0020fills\u0020in\u0020missing\u0020values\u0020in\u0020an\u0020input\u0020array\u0020based\u0020on\u0020a\u0020template\u0020array.",
            "url": "classes/Murdej-Arrays.html#method_addDefaultsRecursive"
        },                {
            "fqsen": "\\Murdej\\Arrays\u003A\u003AsetValue\u0028\u0029",
            "name": "setValue",
            "summary": "Sets\u0020a\u0020value\u0020within\u0020a\u0020nested\u0020array\u0020using\u0020a\u0020specified\u0020path.",
            "url": "classes/Murdej-Arrays.html#method_setValue"
        },                {
            "fqsen": "\\Murdej\\Arrays\u003A\u003AgetValue\u0028\u0029",
            "name": "getValue",
            "summary": "Retrieves\u0020a\u0020value\u0020from\u0020a\u0020nested\u0020array\u0020using\u0020a\u0020specified\u0020path.",
            "url": "classes/Murdej-Arrays.html#method_getValue"
        },                {
            "fqsen": "\\Murdej\\Arrays\u003A\u003Aflatten\u0028\u0029",
            "name": "flatten",
            "summary": "",
            "url": "classes/Murdej-Arrays.html#method_flatten"
        },                {
            "fqsen": "\\Murdej\\Arrays\u003A\u003Aunflatten\u0028\u0029",
            "name": "unflatten",
            "summary": "",
            "url": "classes/Murdej-Arrays.html#method_unflatten"
        },                {
            "fqsen": "\\Murdej\\Arrays\u003A\u003ArenameKeys\u0028\u0029",
            "name": "renameKeys",
            "summary": "Renames\u0020keys\u0020in\u0020an\u0020array\u0020based\u0020on\u0020a\u0020provided\u0020mapping.",
            "url": "classes/Murdej-Arrays.html#method_renameKeys"
        },                {
            "fqsen": "\\Murdej\\CollectionDiff",
            "name": "CollectionDiff",
            "summary": "",
            "url": "classes/Murdej-CollectionDiff.html"
        },                {
            "fqsen": "\\Murdej\\CollectionDiff\u003A\u003Acompare\u0028\u0029",
            "name": "compare",
            "summary": "",
            "url": "classes/Murdej-CollectionDiff.html#method_compare"
        },                {
            "fqsen": "\\Murdej\\CollectionDiff\u003A\u003A\u0024newItems",
            "name": "newItems",
            "summary": "",
            "url": "classes/Murdej-CollectionDiff.html#property_newItems"
        },                {
            "fqsen": "\\Murdej\\CollectionDiff\u003A\u003A\u0024newItemKeys",
            "name": "newItemKeys",
            "summary": "",
            "url": "classes/Murdej-CollectionDiff.html#property_newItemKeys"
        },                {
            "fqsen": "\\Murdej\\CollectionDiff\u003A\u003A\u0024updatedItems",
            "name": "updatedItems",
            "summary": "",
            "url": "classes/Murdej-CollectionDiff.html#property_updatedItems"
        },                {
            "fqsen": "\\Murdej\\CollectionDiff\u003A\u003A\u0024updatedItemKeys",
            "name": "updatedItemKeys",
            "summary": "",
            "url": "classes/Murdej-CollectionDiff.html#property_updatedItemKeys"
        },                {
            "fqsen": "\\Murdej\\CollectionDiff\u003A\u003A\u0024deletedItems",
            "name": "deletedItems",
            "summary": "",
            "url": "classes/Murdej-CollectionDiff.html#property_deletedItems"
        },                {
            "fqsen": "\\Murdej\\CollectionDiff\u003A\u003A\u0024deletedItemKeys",
            "name": "deletedItemKeys",
            "summary": "",
            "url": "classes/Murdej-CollectionDiff.html#property_deletedItemKeys"
        },                {
            "fqsen": "\\Murdej\\CollectionDiffItem",
            "name": "CollectionDiffItem",
            "summary": "",
            "url": "classes/Murdej-CollectionDiffItem.html"
        },                {
            "fqsen": "\\Murdej\\CollectionDiffItem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Murdej-CollectionDiffItem.html#method___construct"
        },                {
            "fqsen": "\\Murdej\\CollectionDiffItem\u003A\u003A\u0024oldValue",
            "name": "oldValue",
            "summary": "",
            "url": "classes/Murdej-CollectionDiffItem.html#property_oldValue"
        },                {
            "fqsen": "\\Murdej\\CollectionDiffItem\u003A\u003A\u0024newValue",
            "name": "newValue",
            "summary": "",
            "url": "classes/Murdej-CollectionDiffItem.html#property_newValue"
        },                {
            "fqsen": "\\Murdej\\CollectionDiffItem\u003A\u003A\u0024key",
            "name": "key",
            "summary": "",
            "url": "classes/Murdej-CollectionDiffItem.html#property_key"
        },                {
            "fqsen": "\\Murdej\\DTO\\Attributes\\ArrayItemType",
            "name": "ArrayItemType",
            "summary": "",
            "url": "classes/Murdej-DTO-Attributes-ArrayItemType.html"
        },                {
            "fqsen": "\\Murdej\\DTO\\Attributes\\ArrayItemType\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Murdej-DTO-Attributes-ArrayItemType.html#method___construct"
        },                {
            "fqsen": "\\Murdej\\DTO\\Attributes\\ArrayItemType\u003A\u003A\u0024itemType",
            "name": "itemType",
            "summary": "",
            "url": "classes/Murdej-DTO-Attributes-ArrayItemType.html#property_itemType"
        },                {
            "fqsen": "\\Murdej\\DTO\\CommonResult",
            "name": "CommonResult",
            "summary": "",
            "url": "classes/Murdej-DTO-CommonResult.html"
        },                {
            "fqsen": "\\Murdej\\DTO\\CommonResult\u003A\u003AgetStatus\u0028\u0029",
            "name": "getStatus",
            "summary": "",
            "url": "classes/Murdej-DTO-CommonResult.html#method_getStatus"
        },                {
            "fqsen": "\\Murdej\\DTO\\CommonResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Murdej-DTO-CommonResult.html#method___construct"
        },                {
            "fqsen": "\\Murdej\\DTO\\CommonResult\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Murdej-DTO-CommonResult.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Murdej\\DTO\\CommonResult\u003A\u003Aerror\u0028\u0029",
            "name": "error",
            "summary": "",
            "url": "classes/Murdej-DTO-CommonResult.html#method_error"
        },                {
            "fqsen": "\\Murdej\\DTO\\CommonResult\u003A\u003Aok\u0028\u0029",
            "name": "ok",
            "summary": "",
            "url": "classes/Murdej-DTO-CommonResult.html#method_ok"
        },                {
            "fqsen": "\\Murdej\\DTO\\CommonResult\u003A\u003AStatusOk",
            "name": "StatusOk",
            "summary": "",
            "url": "classes/Murdej-DTO-CommonResult.html#constant_StatusOk"
        },                {
            "fqsen": "\\Murdej\\DTO\\CommonResult\u003A\u003AStatusError",
            "name": "StatusError",
            "summary": "",
            "url": "classes/Murdej-DTO-CommonResult.html#constant_StatusError"
        },                {
            "fqsen": "\\Murdej\\DTO\\CommonResult\u003A\u003A\u0024errors",
            "name": "errors",
            "summary": "",
            "url": "classes/Murdej-DTO-CommonResult.html#property_errors"
        },                {
            "fqsen": "\\Murdej\\DTO\\CommonResult\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Murdej-DTO-CommonResult.html#property_data"
        },                {
            "fqsen": "\\Murdej\\DTO\\ErrorListMessage",
            "name": "ErrorListMessage",
            "summary": "",
            "url": "classes/Murdej-DTO-ErrorListMessage.html"
        },                {
            "fqsen": "\\Murdej\\DTO\\ErrorListMessage\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Murdej-DTO-ErrorListMessage.html#method___construct"
        },                {
            "fqsen": "\\Murdej\\DTO\\ErrorListMessage\u003A\u003A\u0024field",
            "name": "field",
            "summary": "",
            "url": "classes/Murdej-DTO-ErrorListMessage.html#property_field"
        },                {
            "fqsen": "\\Murdej\\DTO\\ErrorListMessage\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/Murdej-DTO-ErrorListMessage.html#property_message"
        },                {
            "fqsen": "\\Murdej\\DTO\\ListResult",
            "name": "ListResult",
            "summary": "",
            "url": "classes/Murdej-DTO-ListResult.html"
        },                {
            "fqsen": "\\Murdej\\DTO\\ListResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Murdej-DTO-ListResult.html#method___construct"
        },                {
            "fqsen": "\\Murdej\\DTO\\ListResult\u003A\u003AgetIsLast\u0028\u0029",
            "name": "getIsLast",
            "summary": "",
            "url": "classes/Murdej-DTO-ListResult.html#method_getIsLast"
        },                {
            "fqsen": "\\Murdej\\DTO\\ListResult\u003A\u003AgetNextLimitFrom\u0028\u0029",
            "name": "getNextLimitFrom",
            "summary": "",
            "url": "classes/Murdej-DTO-ListResult.html#method_getNextLimitFrom"
        },                {
            "fqsen": "\\Murdej\\DTO\\ListResult\u003A\u003AmapItems\u0028\u0029",
            "name": "mapItems",
            "summary": "",
            "url": "classes/Murdej-DTO-ListResult.html#method_mapItems"
        },                {
            "fqsen": "\\Murdej\\DTO\\ListResult\u003A\u003A\u0024items",
            "name": "items",
            "summary": "",
            "url": "classes/Murdej-DTO-ListResult.html#property_items"
        },                {
            "fqsen": "\\Murdej\\DTO\\ListResult\u003A\u003A\u0024totalCount",
            "name": "totalCount",
            "summary": "",
            "url": "classes/Murdej-DTO-ListResult.html#property_totalCount"
        },                {
            "fqsen": "\\Murdej\\DTO\\ListResult\u003A\u003A\u0024limitFrom",
            "name": "limitFrom",
            "summary": "",
            "url": "classes/Murdej-DTO-ListResult.html#property_limitFrom"
        },                {
            "fqsen": "\\Murdej\\DTO\\ListResult\u003A\u003A\u0024limitCount",
            "name": "limitCount",
            "summary": "",
            "url": "classes/Murdej-DTO-ListResult.html#property_limitCount"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO",
            "name": "SmartDTO",
            "summary": "",
            "url": "classes/Murdej-DTO-SmartDTO.html"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_offsetExists"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_offsetGet"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_offsetSet"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_offsetUnset"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_toArray"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AvalueTo\u0028\u0029",
            "name": "valueTo",
            "summary": "",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_valueTo"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AfromArray\u0028\u0029",
            "name": "fromArray",
            "summary": "",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_fromArray"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AvalueFrom\u0028\u0029",
            "name": "valueFrom",
            "summary": "Pomocn\u00E1\u0020metoda\u0020pro\u0020konverzi\u0020hodnoty\u0020na\u0020z\u00E1klad\u011B\u0020reflexe\u0020vlastnosti.",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_valueFrom"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AparseDateTime\u0028\u0029",
            "name": "parseDateTime",
            "summary": "",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_parseDateTime"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AtoDbValue\u0028\u0029",
            "name": "toDbValue",
            "summary": "Serialize\u0020to\u0020DB",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_toDbValue"
        },                {
            "fqsen": "\\Murdej\\DTO\\SmartDTO\u003A\u003AfromDbValue\u0028\u0029",
            "name": "fromDbValue",
            "summary": "Deserialize\u0020from\u0020DB",
            "url": "classes/Murdej-DTO-SmartDTO.html#method_fromDbValue"
        },                {
            "fqsen": "\\Murdej\\ErrorList",
            "name": "ErrorList",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#method___construct"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003AcheckFill\u0028\u0029",
            "name": "checkFill",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#method_checkFill"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003AcheckPreg\u0028\u0029",
            "name": "checkPreg",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#method_checkPreg"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003AcheckEmail\u0028\u0029",
            "name": "checkEmail",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#method_checkEmail"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003AaddError\u0028\u0029",
            "name": "addError",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#method_addError"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003AgetSrcValue\u0028\u0029",
            "name": "getSrcValue",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#method_getSrcValue"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003AisValid\u0028\u0029",
            "name": "isValid",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#method_isValid"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#method_jsonSerialize"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003A\u0024pathSeparator",
            "name": "pathSeparator",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#property_pathSeparator"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003A\u0024messages",
            "name": "messages",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#property_messages"
        },                {
            "fqsen": "\\Murdej\\ErrorList\u003A\u003A\u0024src",
            "name": "src",
            "summary": "",
            "url": "classes/Murdej-ErrorList.html#property_src"
        },                {
            "fqsen": "\\Murdej\\Errors",
            "name": "Errors",
            "summary": "",
            "url": "classes/Murdej-Errors.html"
        },                {
            "fqsen": "\\Murdej\\Errors\u003A\u003AtoException\u0028\u0029",
            "name": "toException",
            "summary": "",
            "url": "classes/Murdej-Errors.html#method_toException"
        },                {
            "fqsen": "\\Murdej\\Math",
            "name": "Math",
            "summary": "Mathematics\u0020functions",
            "url": "classes/Murdej-Math.html"
        },                {
            "fqsen": "\\Murdej\\Math\u003A\u003AdivideByRate\u0028\u0029",
            "name": "divideByRate",
            "summary": "",
            "url": "classes/Murdej-Math.html#method_divideByRate"
        },                {
            "fqsen": "\\Murdej\\Math\u003A\u003AcompareAccuracy\u0028\u0029",
            "name": "compareAccuracy",
            "summary": "Compares\u0020two\u0020mixed\u0020values\u0020after\u0020rounding\u0020them\u0020based\u0020on\u0020a\u0020specified\u0020accuracy.",
            "url": "classes/Murdej-Math.html#method_compareAccuracy"
        },                {
            "fqsen": "\\Murdej\\Math\u003A\u003AparseFloat\u0028\u0029",
            "name": "parseFloat",
            "summary": "",
            "url": "classes/Murdej-Math.html#method_parseFloat"
        },                {
            "fqsen": "\\Murdej\\PrI\u0028\u0029",
            "name": "PrI",
            "summary": "",
            "url": "namespaces/murdej.html#function_PrI"
        },                {
            "fqsen": "\\Murdej\\ProcI",
            "name": "ProcI",
            "summary": "This\u0020tool\u0020allows\u0020you\u0020to\u0020perform\u0020various\u0020array\u0020operations\u0020such\u0020as\u0020changing\u0020the\u0020stucture,\u0020sorting,\u0020filtering,\u0020mapping\u0020and\u0020more.",
            "url": "classes/Murdej-ProcI.html"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AprepareCallback\u0028\u0029",
            "name": "prepareCallback",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_prepareCallback"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_map"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Aeach\u0028\u0029",
            "name": "each",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_each"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AorderBy\u0028\u0029",
            "name": "orderBy",
            "summary": "Order\u0020by\u0020callback\u0020return\u0020value\u0020of\u0020callback",
            "url": "classes/Murdej-ProcI.html#method_orderBy"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "Filter\u0020elements\u0020by\u0020callback",
            "url": "classes/Murdej-ProcI.html#method_filter"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AfilterKey\u0028\u0029",
            "name": "filterKey",
            "summary": "Retains\u0020only\u0020elements\u0020with\u0020selected\u0020keys.",
            "url": "classes/Murdej-ProcI.html#method_filterKey"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Areverse\u0028\u0029",
            "name": "reverse",
            "summary": "Reverses\u0020the\u0020order\u0020of\u0020the\u0020elements",
            "url": "classes/Murdej-ProcI.html#method_reverse"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Aunique\u0028\u0029",
            "name": "unique",
            "summary": "Removes\u0020duplicates",
            "url": "classes/Murdej-ProcI.html#method_unique"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Astruct\u0028\u0029",
            "name": "struct",
            "summary": "Modifies\u0020the\u0020key\u0020structure\u0020according\u0020to\u0020the\u0020passed\u0020callbacks.",
            "url": "classes/Murdej-ProcI.html#method_struct"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AmapStruct\u0028\u0029",
            "name": "mapStruct",
            "summary": "Modifies\u0020each\u0020element\u0020with\u0020a\u0020callback\u0020and\u0020modifies\u0020the\u0020key\u0020structure\u0020according\u0020to\u0020the\u0020passed\u0020callbacks.",
            "url": "classes/Murdej-ProcI.html#method_mapStruct"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AreduceStruct\u0028\u0029",
            "name": "reduceStruct",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_reduceStruct"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Ashuffle\u0028\u0029",
            "name": "shuffle",
            "summary": "randomizes\u0020the\u0020order\u0020of\u0020the\u0020elements",
            "url": "classes/Murdej-ProcI.html#method_shuffle"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Aslice\u0028\u0029",
            "name": "slice",
            "summary": "Leaves\u0020only\u0020part\u0020of\u0020the\u0020field\u0020between\u0020the\u0020indices.",
            "url": "classes/Murdej-ProcI.html#method_slice"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Areduce\u0028\u0029",
            "name": "reduce",
            "summary": "Perform\u0020on\u0020the\u0020elements\u0020reduce.\u0020Unlike\u0020most\u0020other\u0020methods,\u0020it\u0020returns\u0020the\u0020result\u0020of\u0020reduce\u0020and\u0020does\u0020not\u0020modify\u0020the\u0020internal\u0020array.",
            "url": "classes/Murdej-ProcI.html#method_reduce"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Afirst\u0028\u0029",
            "name": "first",
            "summary": "Returns\u0020the\u0020first\u0020element",
            "url": "classes/Murdej-ProcI.html#method_first"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method___construct"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "Returns\u0020elements\u0020as\u0020array",
            "url": "classes/Murdej-ProcI.html#method_toArray"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Avalues\u0028\u0029",
            "name": "values",
            "summary": "Keep\u0020values\u0020only,\u0020remove\u0020keys.\u0020Applies\u0020\u0060array_values\u0060\u0020to\u0020internal\u0020arrays.",
            "url": "classes/Murdej-ProcI.html#method_values"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Akeys\u0028\u0029",
            "name": "keys",
            "summary": "Keep\u0020keys\u0020only\u0020as\u0020values.\u0020Applies\u0020\u0060array_keys\u0060\u0020to\u0020internal\u0020arrays.",
            "url": "classes/Murdej-ProcI.html#method_keys"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003Afrom\u0028\u0029",
            "name": "from",
            "summary": "Create\u0020instance\u0020of\u0020ProcI",
            "url": "classes/Murdej-ProcI.html#method_from"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AcartesianProduct\u0028\u0029",
            "name": "cartesianProduct",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_cartesianProduct"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AfromCartesian\u0028\u0029",
            "name": "fromCartesian",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_fromCartesian"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AreduceBy\u0028\u0029",
            "name": "reduceBy",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_reduceBy"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AselectFields\u0028\u0029",
            "name": "selectFields",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_selectFields"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AcbValue\u0028\u0029",
            "name": "cbValue",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_cbValue"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AfirstKey\u0028\u0029",
            "name": "firstKey",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_firstKey"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AdeepMap\u0028\u0029",
            "name": "deepMap",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_deepMap"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AallMeets\u0028\u0029",
            "name": "allMeets",
            "summary": "Returns\u0020true\u0020if\u0020the\u0020passed\u0020condition\u0020applies\u0020to\u0020all\u0020elements\u0020or\u0020the\u0020array\u0020is\u0020empty",
            "url": "classes/Murdej-ProcI.html#method_allMeets"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AanyMeets\u0028\u0029",
            "name": "anyMeets",
            "summary": "Returns\u0020true\u0020if\u0020the\u0020passed\u0020condition\u0020is\u0020valid\u0020for\u0020at\u0020least\u0020one\u0020element",
            "url": "classes/Murdej-ProcI.html#method_anyMeets"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AallAre\u0028\u0029",
            "name": "allAre",
            "summary": "Returns\u0020true\u0020if\u0020all\u0020elements\u0020are\u0020equal\u0020to\u0020the\u0020passed\u0020value.",
            "url": "classes/Murdej-ProcI.html#method_allAre"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AanyIs\u0028\u0029",
            "name": "anyIs",
            "summary": "Returns\u0020true\u0020if\u0020at\u0020least\u0020one\u0020element\u0020is\u0020equal\u0020to\u0020the\u0020passed\u0020value.",
            "url": "classes/Murdej-ProcI.html#method_anyIs"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003A_deepMap\u0028\u0029",
            "name": "_deepMap",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method__deepMap"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003AiterSrc\u0028\u0029",
            "name": "iterSrc",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#method_iterSrc"
        },                {
            "fqsen": "\\Murdej\\ProcI\u003A\u003A\u0024src",
            "name": "src",
            "summary": "",
            "url": "classes/Murdej-ProcI.html#property_src"
        },                {
            "fqsen": "\\Murdej\\ProcIReduceField",
            "name": "ProcIReduceField",
            "summary": "",
            "url": "classes/Murdej-ProcIReduceField.html"
        },                {
            "fqsen": "\\Murdej\\ProcIReduceField\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Murdej-ProcIReduceField.html#method___construct"
        },                {
            "fqsen": "\\Murdej\\ProcIReduceField\u003A\u003A\u0024fieldName",
            "name": "fieldName",
            "summary": "",
            "url": "classes/Murdej-ProcIReduceField.html#property_fieldName"
        },                {
            "fqsen": "\\Murdej\\ProcIReduceField\u003A\u003A\u0024getCallback",
            "name": "getCallback",
            "summary": "",
            "url": "classes/Murdej-ProcIReduceField.html#property_getCallback"
        },                {
            "fqsen": "\\Murdej\\ProcIReduceField\u003A\u003A\u0024reduceCallback",
            "name": "reduceCallback",
            "summary": "",
            "url": "classes/Murdej-ProcIReduceField.html#property_reduceCallback"
        },                {
            "fqsen": "\\Murdej\\ProcIReduceField\u003A\u003A\u0024initValue",
            "name": "initValue",
            "summary": "",
            "url": "classes/Murdej-ProcIReduceField.html#property_initValue"
        },                {
            "fqsen": "\\Murdej\\StringWalk",
            "name": "StringWalk",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#method___construct"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003Atrace\u0028\u0029",
            "name": "trace",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#method_trace"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003AgetLeftSrc\u0028\u0029",
            "name": "getLeftSrc",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#method_getLeftSrc"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003AfindNext\u0028\u0029",
            "name": "findNext",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#method_findNext"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003AfindNextPreg\u0028\u0029",
            "name": "findNextPreg",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#method_findNextPreg"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003AsaveMark\u0028\u0029",
            "name": "saveMark",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#method_saveMark"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003Agoto\u0028\u0029",
            "name": "goto",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#method_goto"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003AtoEndChunk\u0028\u0029",
            "name": "toEndChunk",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#method_toEndChunk"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003Asubstr\u0028\u0029",
            "name": "substr",
            "summary": "substr\u0028\u0029\u0020\u002D\u0020from\u0020last\u0020mark\u0020to\u0020actual\u0020position\nsubstr\u0028\u0024mark\u0029\u0020\u002D\u0020from\u0020mark\u0020to\u0020from\u0020actual\u0020position\nsubstr\u0028\u0024mark1,\u0020\u0024mark2\u0029\u0020\u002D\u0020from\u0020mark1\u0020to\u0020mark2",
            "url": "classes/Murdej-StringWalk.html#method_substr"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003AsrcLen\u0028\u0029",
            "name": "srcLen",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#method_srcLen"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003AstartsWith\u0028\u0029",
            "name": "startsWith",
            "summary": "Check\u0020if\u0020left\u0020string\u0020starts\u0020with\u0020entered\u0020string",
            "url": "classes/Murdej-StringWalk.html#method_startsWith"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003AfindCurrent\u0028\u0029",
            "name": "findCurrent",
            "summary": "Check\u0020if\u0020left\u0020string\u0020starts\u0020with\u0020entered\u0020string",
            "url": "classes/Murdej-StringWalk.html#method_findCurrent"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003AEnd",
            "name": "End",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#constant_End"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003A\u0024src",
            "name": "src",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#property_src"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003A\u0024mark",
            "name": "mark",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#property_mark"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003A\u0024pos",
            "name": "pos",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#property_pos"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003A\u0024debug",
            "name": "debug",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#property_debug"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003A\u0024debugCallback",
            "name": "debugCallback",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#property_debugCallback"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003A\u0024lastChunk",
            "name": "lastChunk",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#property_lastChunk"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003A\u0024lastChunkNum",
            "name": "lastChunkNum",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#property_lastChunkNum"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003A\u0024lastMarkName",
            "name": "lastMarkName",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#property_lastMarkName"
        },                {
            "fqsen": "\\Murdej\\StringWalk\u003A\u003A\u0024lastMatch",
            "name": "lastMatch",
            "summary": "",
            "url": "classes/Murdej-StringWalk.html#property_lastMatch"
        },                {
            "fqsen": "\\Murdej\\TreeItem",
            "name": "TreeItem",
            "summary": "",
            "url": "classes/Murdej-TreeItem.html"
        },                {
            "fqsen": "\\Murdej\\TreeItem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Murdej-TreeItem.html#method___construct"
        },                {
            "fqsen": "\\Murdej\\TreeItem\u003A\u003A\u0024item",
            "name": "item",
            "summary": "",
            "url": "classes/Murdej-TreeItem.html#property_item"
        },                {
            "fqsen": "\\Murdej\\TreeItem\u003A\u003A\u0024children",
            "name": "children",
            "summary": "",
            "url": "classes/Murdej-TreeItem.html#property_children"
        },                {
            "fqsen": "\\Murdej\\TreeItem\u003A\u003A\u0024level",
            "name": "level",
            "summary": "",
            "url": "classes/Murdej-TreeItem.html#property_level"
        },                {
            "fqsen": "\\Murdej\\TreeItem\u003A\u003A\u0024parent",
            "name": "parent",
            "summary": "",
            "url": "classes/Murdej-TreeItem.html#property_parent"
        },                {
            "fqsen": "\\Murdej\\TreeMaker",
            "name": "TreeMaker",
            "summary": "",
            "url": "classes/Murdej-TreeMaker.html"
        },                {
            "fqsen": "\\Murdej\\TreeMaker\u003A\u003Amake\u0028\u0029",
            "name": "make",
            "summary": "",
            "url": "classes/Murdej-TreeMaker.html#method_make"
        },                {
            "fqsen": "\\Murdej\\TreeMaker\u003A\u003Alinearize\u0028\u0029",
            "name": "linearize",
            "summary": "",
            "url": "classes/Murdej-TreeMaker.html#method_linearize"
        },                {
            "fqsen": "\\Murdej\\TreeMaker\u003A\u003AfindFirst\u0028\u0029",
            "name": "findFirst",
            "summary": "Find\u0020first\u0020matching\u0020node",
            "url": "classes/Murdej-TreeMaker.html#method_findFirst"
        },                {
            "fqsen": "\\Murdej\\TreeMaker\u003A\u003Apath\u0028\u0029",
            "name": "path",
            "summary": "",
            "url": "classes/Murdej-TreeMaker.html#method_path"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Murdej",
            "name": "Murdej",
            "summary": "",
            "url": "namespaces/murdej.html"
        },                {
            "fqsen": "\\Murdej\\DTO\\Attributes",
            "name": "Attributes",
            "summary": "",
            "url": "namespaces/murdej-dto-attributes.html"
        },                {
            "fqsen": "\\Murdej\\DTO",
            "name": "DTO",
            "summary": "",
            "url": "namespaces/murdej-dto.html"
        }            ]
);
